// src/config.rs

pub const NEGATIVE_PROMPT: &str = "bad anatomy, bad hands, missing fingers, extra fingers, bad arms, missing legs, missing arms, poorly drawn face, bad face, fused face, cloned face, three crus, fused feet, fused thigh, extra crus, ugly fingers, horn, realistic photo, huge eyes, worst face, 2girl, long fingers, disconnected limbs, paintings, cartoon, anime, lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, skin spots, acnes, skin blemishes, age spot, glans, extra nipples, fewer nipples, bad nipples, bad breast, bad body, bad face, bad eyes, bad mouth, bad nose, bad ears, bad hair, bad fingers, bad toes";

pub fn get_prompts() -> Vec<&'static str> {
    vec![
        "(photorealistic:1.3), (highly detailed skin texture:1.2), masterpiece, best quality, 1girl, solo, cute, pink hair, blue eyes, short hair, smile, blush, looking at viewer",
        "(photorealistic:1.3), (highly detailed skin texture:1.2), a realistic 20-year-old blonde man as Naruto Uzumaki, spiky realistic blonde hair, intense blue eyes with realistic irises, iconic whisker marks as faint scars on cheeks, wearing a weathered orange and black tactical jacket, standing outdoors. Beautiful sunshine, golden hour, bright sunbeams, lens flare, rim lighting. Cinematic lighting, 8k, masterpiece, depth of field, bokeh, sharp focus, shot on 50mm lens.",
        "raw photo, 1girl, asian, pink bob cut, soft studio lighting, high-detail skin, sharp focus, 8k uhd, dslr, soft bokeh, high quality, film grain, masterpiece, (photorealistic:1.3), (highly detailed skin texture:1.2), best quality, solo, cute, blue eyes, short hair, smile, blush, looking at viewer, turtleneck sweater, indoors",
        "(extreme photorealistic:1.3), a high-detail hybrid creature, (head of a domestic tabby cat:1.2) seamlessly merged with the (body and wings of a brown owl:1.2), cat-owl chimera, Meowl, perched on a mossy wooden branch, wide curious feline eyes, intricate feather textures mixed with soft fur, sharp owl talons, (bokeh background:1.1), soft natural meadow lighting, golden hour, 8k resolution, highly detailed plumage, masterpiece, raw photo, f/2.8, 85mm lens, sharp focus on eyes, owl-cat hybrid, (photorealistic:1.3), (highly detailed skin texture:1.2), best quality, solo, cute, looking at viewer, owl wings, cat ears, indoors, owl feet",
    ]
}
